set(CMAKE_SYSTEM_NAME Generic)

set(TOOLCHAIN_PREFIX)
set(TARGET_TRIPLET arm-none-eabi)
set(PLATFORM_SUFFIX)

set(CMAKE_EXECUTABLE_SUFFIX_CXX ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_C ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_ASM ".elf")



set(CMAKE_C_COMPILER "${TOOLCHAIN_PREFIX}${TARGET_TRIPLET}-gcc${PLATFORM_SUFFIX}")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PREFIX}${TARGET_TRIPLET}-g++${PLATFORM_SUFFIX}")
set(CMAKE_ASM_COMPILER "${TOOLCHAIN_PREFIX}${TARGET_TRIPLET}-gcc${PLATFORM_SUFFIX}")
set(CMAKE_CXX_LINK_EXECUTABLE "<CMAKE_CXX_COMPILER> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> -Wl,--start-group <OBJECTS> <LINK_LIBRARIES> -Wl,--end-group -o <TARGET>")
set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)

set(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}${TARGET_TRIPLET}-objcopy${PLATFORM_SUFFIX} CACHE INTERNAL "objcopy tool")
set(CMAKE_OBJDUMP ${TOOLCHAIN_PREFIX}${TARGET_TRIPLET}-objdump${PLATFORM_SUFFIX} CACHE INTERNAL "objdump tool")
set(CMAKE_SIZE ${TOOLCHAIN_PREFIX}${TARGET_TRIPLET}-size${PLATFORM_SUFFIX} CACHE INTERNAL "size tool")
set(CMAKE_AR ${TOOLCHAIN_PREFIX}${TARGET_TRIPLET}-ar${PLATFORM_SUFFIX} CACHE INTERNAL "archive tool")
set(CMAKE_DEBUGER ${TOOLCHAIN_PREFIX}${TARGET_TRIPLET}-gdb${PLATFORM_SUFFIX} CACHE INTERNAL "debuger")
set(CMAKE_C_USE_RESPONSE_FILE_FOR_INCLUDES 1)
set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES 1)
